version: '3'

volumes: 
  rails_gems:
  react_node_modules:
  mysql_data:

services: 
  db: 
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:8.0
    volumes: 
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
    ports: 
      - "${DB_PORT}:3306"

  back:
    container_name: back
    build:
      context: .
      dockerfile: Dockerfile_rails
    volumes: 
      - ./back:/usr/src/app:cached
      - rails_gems:/usr/local/bundle
    expose:
      - '3000'
    ports: 
      - "${RAILS_PORT}:3000"
    command: bash -c "chmod 755 /usr/src/app/scripts/rails_start.sh && /usr/src/app/scripts/rails_start.sh"
    depends_on:
      - db

  front:
    container_name: front
    build: 
      context: .
      dockerfile: Dockerfile_react
    volumes: 
      - ./front:/usr/src/app:cached
      - react_node_modules:/usr/src/app/node_modules
    stdin_open: true
    tty: true
    expose: 
      - '3000'
    ports:
      - "${REACT_PORT}:3000"
    command: yarn start
    depends_on:
      - back