version: '3'

volumes: 
  rails_data:
  mysql_data:

services: 
  db: 
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:8.0
    volumes: 
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
    ports: 
      - "${DB_PORT}:3306"

  back:
    container_name: back
    build:
      context: .
      dockerfile: Dockerfile_rails
    volumes: 
      - ./back:/usr/src/app
      - rails_data:/usr/local/bundle
    expose:
      - '3000'
    ports: 
      - "${RAILS_PORT}:3000"
    command: bundle exec rails server -b '0.0.0.0'
    depends_on:
      - db

  front:
    container_name: front
    build: 
      context: .
      dockerfile: Dockerfile_react
    volumes: 
      - ./front:/usr/src/app
    stdin_open: true
    tty: true
    expose: 
      - '3000'
    ports:
      - "${REACT_PORT}:3000"
    command: yarn start
    depends_on:
      - back